#!/bin/bash

cd /tmp

if ls /tmp/toold > /dev/null 2>&1
then

    if ls /tmp/rinex_de > /dev/null 2>&1
    then
        rm /tmp/rinex_de
        cd /tmp
        /usr/bin/python /root/SDR/getrinex_us.py
	#wget http://aprs.ehamnet.cz/gps_rinex.txt -O rinex
    else
        touch /tmp/rinex_de
        cd /tmp
        /usr/bin/python /root/SDR/getrinex_de.py                #de
    fi
    rm /tmp/toold
    sleep 20
    rm /tmp/toold

fi
